### ISSUE TITLE
Arabadzhiev - The `SyncSynthVault` implementation is vulnerable to inflation attacks

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-amphor-judging#129]
Arabadzhiev

high

# The `SyncSynthVault` implementation is vulnerable to inflation attacks

## Summary
The current implementation of the `SyncSynthVault::deposit` function can lead to the loss of assets for some users

## Vulnerability Detail
The `AsyncSynthVault` contract inherits the `SyncSynthVault` abstract contract. Due to the way that it is currently implemented, the `SyncSynthVault::deposit` function (which is not overrided in `AsyncSynthVault`) is vulnerable to the infamous "vault inflation attack". Although it does use virtual shares, just like the OpenZeppelin ERC4626 implementation, since those are always fixed to the value of 1, they will not suffice in preventing the attack from happening.

To illustrate how this can be exploited, let's take an example: 

1. Bob sends a transaction to deposit 1000 USDC into the Amphor vault.
2. Unfortunately for him, Alice has been carefully monitoring the mempool, so after she sees his transaction, she frontruns it with two transactions of her own - one that deposits 100 USDC into the vault (which she receives 100 shares for) and another that directly transfers 1001 USDC to it (which brings up its share price from 1 to 1001 USDC).
3. The transaction of Bob gets executed - He receives 0 shares for his deposit
4. Now Alice executes another transaction that redeems all of her shares - She receives 100 × 2102 ÷ 101 = **2081 shares**

Although it is stated in the contest README that the protocol team intends to "bootstrap" their vaults by depositing into the vaults first themselves in order to protect against that attack, this will actually have the opposite effect for them - Instead of protecting their protocol against the attack, they themself will most likely get exploited when performing the bootstrap deposits.

## Impact
Some users might receive less/no shares when depositing their assets into the vault

## Code Snippet
[SyncSynthVault.sol#L300-L317](https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L300-L317)

## Tool used
Manual Review

## Recommendation
Revert when the `sharesAmount` is equal to 0. Additionally, you might also want to increase the virtual shares count.

Duplicate of #50

**Comment by aslanbekaibimov** [comment]
Hey @Arabadzhiew 

In your PoC, during step 2, Alice deposits 100 USDC and receives 100 shares. Then she donates 1001 USDC. So there would be 101 shares (100 Alice's and 1 virtual), representing 1102 USDC (1101 from Alice and 1 virtual), share price = 1102 / 101 = 10.

But you claim that the share price will actually become 1001 USDC, not 10. Could you please explain how did you get this value?

**Comment by Arabadzhiew** [comment]
Hey @aslanbekaibimov, you are actually right, good catch. Not sure what I was thinking when writing that PoC. 

However, the point made in the report still holds true - The vulnerability is indeed present, it's just that the exploit scenario will have to be different. In the case where Alice first deposits 100 USDC, she will then have to donate 101001 USDC in order to bring the share price up to 1001 USDC. 

The exploit can also be performed with a much smaller initial deposit. For example, if Alice makes an initial deposit of 3 USDC, then she will have to donate only 4001 USDC in order to carry out the exploit. The end result for Bob will still be the same - He will get no shares in return for his deposit.

**Comment by Arabadzhiew** [comment]
After a further private discussion with @aslanbekaibimov, we came to the conclusion that this issue will actually never be profitable to the attacker performing the exploit, due to the use of virtual shares. The attacker will always be at a loss, but depending on the amount of assets that they have available, they can bring their loss to close to a zero. The negative impact is still present though - The first depositor will lose their deposited assets, given the right conditions.
