### ISSUE TITLE
0xShax2nk.in - depositWithPermit Functionality Limited to Permit Creator Only

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-amphor-judging#14]
0xShax2nk.in

medium

# depositWithPermit Functionality Limited to Permit Creator Only

## Summary

The `depositWithPermit` function in the SyncSynthVault contract is designed to leverage ERC-20 token permits for depositing tokens into the vault. However, due to a flaw in current implementation, only the signer of the permit can call this function, which contradicts the intended use of permits.

## Vulnerability Detail

The `depositWithPermit` function is intended to allow a user to give permission to another entity (typically a contract) to deposit on their behalf using a signed message (permit). The current implementation restricts this functionality because it requires the permit signer to be the same as the message sender (**msg.sender**), which defeats the purpose of the permit system.

The `execPermit` function should verify that the permit was signed by the owner (the actual owner of the funds) and not necessarily the **msg.sender**. The contract should be modified to accept a permit from any signer and then allow any entity to perform the deposit using that permit, as long as the permit is valid and the receiver matches the intended beneficiary specified in the permit.

## Impact

This implementation error restricts the functionality of the permit system, preventing third-party contracts or users from depositing on behalf of the permit signer. 

## Code Snippet

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L277

## PoC

Consider a following scenario 

1. Alice wants to deposit tokens into the SyncSynthVault without directly interacting with the contract. She signs a permit granting the vault contract permission to transfer her tokens.
2. Alice sends the signed permit to Bob, who is a service provider that handles deposits.
3. Bob attempts to call depositWithPermit using Alice's permit to deposit tokens into the vault on her behalf.
4. The transaction fails because Bob is not the signer of the permit, even though he has a valid permit from Alice.

## Tool used

Manual Review

## Recommendation

The depositWithPermit function should be modified to accept a permit from any signer and allow any entity (msg.sender) to perform the deposit using that permit, as long as the permit is valid.

- Add an owner field to the PermitParams struct to explicitly specify the permit signer.
- Update the depositWithPermit function to use the owner from PermitParams when calling execPermit.

```diff
struct PermitParams {
+    address owner; // Signer of the permit
    uint256 value;
    uint256 deadline;
    uint8 v;
    bytes32 r;
    bytes32 s;
}
```
```diff
function depositWithPermit(
    uint256 assets,
    address receiver,
    PermitParams calldata permitParams
)
    external
    returns (uint256)
{
    // Use the permit signer's address for the permit execution
-     execPermit(_msgSender(), address(this), permitParams);
+    execPermit(permitParams.owner, address(this), permitParams);
    // Continue with the deposit process
    return deposit(assets, receiver);
}
```

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/106

**Comment by Atharv181** [comment]
Escalate

I'm escalating this issue on behalf of @0xShax2nk.in for the following reasons he provided: 


The issue falls under medium severity indeed, as the current implementation restricts the use of the permit to the signer only, defeating the purpose of the permit system which is meant to delegate the ability to perform actions on the signer's behalf. 

There is an inconsistency in the use of permits with the depositWithPermit function:

- The execPermit function is called with _msgSender() as the owner, implying that the caller of depositWithPermit must be the permit signer.
- The intended use of permits is to allow a third party to execute actions with the signer's approval without requiring the signer to be the caller.

I see the comment left during judging, 

> another goal of permit is to create off-chain approvals; plus I don't see it breaking core functionality of the contract; yeah it would be more convenient; but it's a design advice -> info/low


I disagree with the comment, even if another goal of permit is to create off-chain approvals, the full potential of this feature includes not just creating off-chain approvals but also enabling third parties to use these approvals on-chain on behalf of the signer. off-chain approvals are a goal, they should not compromise the intended security model of the permit system, which includes delegating the execution of approved actions.

Also I don't consider it as design advice, rather the logic(code) should be corrected in order to keep consistency with the ERC20 permit standard. Deviating from the standard's typical implementation could lead to compatibility issues with wallets and other smart contracts that expect the standard behavior and this implies the one of the core feature of contract is restricted.

The solution is simple is to Modify the depositWithPermit function to accept the permit signer's address as an argument and use it in the execPermit call instead of _msgSender(), as recommended in mitigation of the original report.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I'm escalating this issue on behalf of @0xShax2nk.in for the following reasons he provided: 
> 
> 
> The issue falls under medium severity indeed, as the current implementation restricts the use of the permit to the signer only, defeating the purpose of the permit system which is meant to delegate the ability to perform actions on the signer's behalf. 
> 
> There is an inconsistency in the use of permits with the depositWithPermit function:
> 
> - The execPermit function is called with _msgSender() as the owner, implying that the caller of depositWithPermit must be the permit signer.
> - The intended use of permits is to allow a third party to execute actions with the signer's approval without requiring the signer to be the caller.
> 
> I see the comment left during judging, 
> 
> > another goal of permit is to create off-chain approvals; plus I don't see it breaking core functionality of the contract; yeah it would be more convenient; but it's a design advice -> info/low
> 
> 
> I disagree with the comment, even if another goal of permit is to create off-chain approvals, the full potential of this feature includes not just creating off-chain approvals but also enabling third parties to use these approvals on-chain on behalf of the signer. off-chain approvals are a goal, they should not compromise the intended security model of the permit system, which includes delegating the execution of approved actions.
> 
> Also I don't consider it as design advice, rather the logic(code) should be corrected in order to keep consistency with the ERC20 permit standard. Deviating from the standard's typical implementation could lead to compatibility issues with wallets and other smart contracts that expect the standard behavior and this implies the one of the core feature of contract is restricted.
> 
> The solution is simple is to Modify the depositWithPermit function to accept the permit signer's address as an argument and use it in the execPermit call instead of _msgSender(), as recommended in mitigation of the original report.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Thank you for the comment and rasing this problem, also thank you for correcting my comment. But I still think this should remain low/info, I don't see it as a core functionality of the protocol and more of a "nice feature to have", therefore, I believe it's only an oppotunity loss. Maybe my assumption is wrong here, but I believe it doesn't break core functionality.

Users still can freely interact with the protocol via non-permit functions, also no funds are lost here, cause the txn would just revert. Therefore, I believe it's a low (I don't say it's completely wrong, but believe it's low severity).

**Comment by 0xShax2nk** [comment]
Like I stated in above comments, there is reason why permit feature is implemented in the contract, but since it is not implemented correctly it do not adheres to the standard compliance. As demonstrated in PoC part, if Alice sends the signed permit to Bob, who is service provider that handles deposits. Where Bob could be any third party wallet or smart contract, which will not work correctly due to inconsistency in current implementation as stated.


> Users still can freely interact with the protocol via non-permit functions

I agree users can still freely interact with the protocol but that doesn't discard the issue as it is one of the expected user scenarios, for which the permit feature is used in the contract or system. Even if the protocol is itself not implementing any external integrations, users are expected to use them for deposits through permit feature or maybe for other actions also. 


> I don't see it as a core functionality of the protocol and more of a "nice feature to have"

I disagree with the comment this is nice to have feature and believe the logic should be corrected in order to adhere to the standard behavior of the permit feature. 


Adding links to the similar issue [report](https://code4rena.com/reports/2023-07-pooltogether#m-25-depositwithpermit-and-mintwithpermit-are-allowed-to-be-called-by-the-permit-creator-only) for refs.

Also according to Sherlock judging rule book, the issue falls under valid medium as third party's would require strong compliance with the EIP's implemented in the code and it also creates adverse effects.

**Comment by WangSecurity** [comment]
I want to again highlight that I've said in my previous comment. I do NOT say this report is wrong, I think it's correct. I do NOT say it shouldn't be corrected. I do NOT say it works properly. But I do say that it's either low or info. If it was a core functionality break, then users wouldn't be able to interact with the protocol freely, therefore, I believe it's only an opportunity loss.

With this feature not working, not much changes, users still can interact with the protocol, everything works, we just cannot use permits, I don't see it as either H or M.

**Comment by 0xShax2nk** [comment]
While the permit feature may not be core to the protocol's basic functionality, it is a significant part of the ERC20 standard's extended functionality. Its incorrect implementation can be misleading as users and third party integrations expect a feature labeled as "permit" to work according to the standard.

`depositWithPermit` function is public and external intended to be accessed by users or third party integrations makes it one of the core functionality of the contract. I believe sponsors would agree this being the part of the core functionality of the contract even though it doesn't deal with funds there is reason why it is implemented is to provide a feature to the users. So do not look at it as only opportunity loss, consider not following EIP compliance which creates adverse effect to the contracts expected functionality.

**Comment by 0xHacker2684** [comment]
This issue was already found in previous contest as medium so why it can't be medium severity here 
See previous audit report of same issue -https://solodit.xyz/issues/m-25-depositwithpermit-and-mintwithpermit-are-allowed-to-be-called-by-the-permit-creator-only-code4rena-pooltogether-pooltogether-git

**Comment by WangSecurity** [comment]
Issues found in past contests doesn't mean they should be valid in every contest, every protocol is at some point unique, therefore, we should treat them in this way.

Also replying to 0xShax2nk, as you say it's an extended functionality of ERC20, not even the main/core one. And I agree that's really good for the protocol to have it, but I really struggle to see how it breaks the core functionality. Nothing personal against you, it's just how I see the situation. Maybe I'm biased cause I don't want to get penalty for accepted escalation :) But if the head of judging decides it valid, then so be it. It'll be a very good, tho costly, lesson to learn.

Thank you for bringing up this issue, maybe it has more than I thought initially and despite the decision, any of us can learn something new here.

**Comment by 0xShax2nk** [comment]
I absolutely understand your point of view. You are doing your job as a judge, am doing my job as Watson, nothing much. Let's leave it to the team to make final decisions as you said.

**Comment by Evert0x** [comment]
> Like I stated in above comments, there is reason why permit feature is implemented in the contract, but since it is not implemented correctly...

The permit feature is implemented correctly, it's just not implemented completely across all relevant functions. 

I agree with the other arguments brought up by Wang. This report doesn't indicate anything that could lead to a loss, it's a recommendation to change the functionality of the contracts.

Planning to reject and keep issue state as is

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Atharv181](https://github.com/sherlock-audit/2024-03-amphor-judging/issues/14/#issuecomment-2028001729): rejected

**Comment by zzykxx** [comment]
This has been marked as "will fix" but it's not fixed.
