### ISSUE TITLE
smbv-1923 - Bootstraping vault with mentioned values would create bad debt.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-amphor-judging#142]
smbv-1923

high

# Bootstraping vault with mentioned values would create bad debt.

## Summary
The mentioned Bootstrapped liquidity added by protocol would not be owned by anyone and this liquidity would not be redeemed or withdraw in future time so this bootstrapped liquidity would accrue yield from vault creating bad debt.

## Vulnerability Detail
- As mentioned by team they would be Bootstrapping the vault.
```solidity
We will boostrap the vault to avoid inflation attack so please take this into consideration.
For weth vault it would be 1 weth.
For usdc vault it would be 1000 usdc.
```
- Let's take example of WETH token , in WETH vault they are Bootstrapping 1 WETH to avoid inflation attack but 1 WETH is very big 
number ( 1e18 wei) and the yield generated from 1 WETH is stolen from the actual suppliers which leads to loss of yield funds for users.  Note that the Bootstrapped share price of 10**18 cannot be ignored, one can increase the supply share price, and the Bootstrapped Shares will have a bigger claim on the total asset percentage.
-  Thus leading to loss of yield to actual suppliers/users.
- At one point we can even neglect the yield which is generated from bootstrapping 1e3 wei of assets but bootstrapping 10**18 wei of assest would create big difference and the impact would linearly increase as time passes by.
## Impact

The yield generated from bootstrapped liquidity would not be claimed by anyone thus the yield accrued from this bootstrapped liquidity leads to loss of yield funds for users.
## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L576
## Tool used

Manual Review
Taken reference from `Morpho Blue` contest where similar bug was submitted by `cmichel` and it was accepted.

## Recommendation

-Bootsrapping liquidity should be reduced and can be made 10**3 wei of assets like how Uniswap does.

-Another suggestion  is to use ERC4626 Upgradeable contracts.

-Elaborating why 1e3 wei of assets would be sufficient to prevent inflation attack. By even using 10**3 wei as bootstrapped amount the attacker have to minimum donate 1000x assests to contract for minting 0 shares to user and in against the attacker would be losing 50% of donated amount to the virtual share which you have implemented in the contract. Taking example a trusted user deposit 10 ether, now for attacker to mint them zero shares they would have to donate a minimum of 10000 ether which is infeasible and even if attacker donates this big amount he would loose a percentage of assest to virtual share according to situation, making attack infeasible for attacker.

**Comment by MD-YashShah1923** [comment]
- This is not a design decision, and even if it is design decision it is at cost of user's loss of yield .
- Bootstrapping with 1 WETH and 1000 USDC not only causes loss of yield for users but the protocol team losing 1 WETH and 1000 USDC which is  big number and this amount can be easily prevented by only bootstrapping 1000 wei of assests for any token.
- By bootstrapping 1000 wei this can easily prevent inflation attack as attacker have to deposit  in 1000x tokens to make user mint zero shares which is not all feasible for attacker thus preventing inflation attack ( for example see above report of mine). 
- And the yield which keeps accruing due to bootstrapping liquidity would not be claimed by anybody and the figure keeps increasing with time thus user losing funds as he cannot claim these locked funds . 
- And as bootstrapping amount is big it would take less time and accrual of yield becomes faster.

- For reference :
- The same type of issue was submitted by "CMICHEL" on cantina and was accepted.

https://cantina.xyz/code/d86b7f95-e574-4092-8ea2-78dcac2f54f1/findings/ab131188-3caa-4314-a5f2-6b2ee9f939de?q=status%253Anew%252Cdisputed%252Crejected%252Cduplicate%252Cconfirmed%252Cacknowledged%252Cfixed%252Cescalated%2520reviewers%253Acmichel

@WangSecurity @Czar102 @blablalf @GuiDupont

**Comment by blablalf** [comment]
> * Let's take example of WETH token , in WETH vault they are Bootstrapping 1 WETH to avoid inflation attack but 1 WETH is very big
>   number ( 1e18 wei) and the yield generated from 1 WETH is stolen from the actual suppliers which leads to loss of yield funds for users.

Hello @MD-YashShah1923, 
The bootstrap is made thank to a deposit. I don't see where something would be stolen since we are depositing like any normal user.

**Comment by MD-YashShah1923** [comment]
Hello @blablalf @WangSecurity @Czar102 @GuiDupont 
- The Bootstrapped supply shares, that are not owned by anyone, earn yield  in vault. This yield is stolen from the actual suppliers which leads to loss of yield funds for users. Note that while the initial share price of 1e-18 for WETH might make it seem like the Bootstrapped shares can be ignored, one can increase the supply share price and the Bootstrapped shares will have a bigger claim on the total asset percentage.
- And another thing @blablalf , you and your team can easily prevent inflation attack by only bootstrapping 1000 wei of WETH and not 1e-18 wei of WETH where the inflation attack gets prevented and the team also saves money . So bootstrapping with this much big amount is of no use.

**Comment by MD-YashShah1923** [comment]
https://cantina.xyz/code/d86b7f95-e574-4092-8ea2-78dcac2f54f1/findings/abdc5508-2320-48f1-8a0b-1e6b5c30cc7e?q=status%253Anew%252Cdisputed%252Crejected%252Cduplicate%252Cconfirmed%252Cacknowledged%252Cfixed%252Cescalated

**Comment by blablalf** [comment]
> Hello @blablalf @WangSecurity @Czar102 @GuiDupont
> 
> * The Bootstrapped supply shares, that are not owned by anyone, earn yield  in vault. This yield is stolen from the actual suppliers which leads to loss of yield funds for users. Note that while the initial share price of 1e-18 for WETH might make it seem like the Bootstrapped shares can be ignored, one can increase the supply share price and the Bootstrapped shares will have a bigger claim on the total asset percentage.
> * And another thing @blablalf , you and your team can easily prevent inflation attack by only bootstrapping 1000 wei of WETH and not 1e-18 wei of WETH where the inflation attack gets prevented and the team also saves money . So bootstrapping with this much big amount is of no use.

As I said the bootstrap is made with a normal deposit (so thx to an underlying deposit from us), the shares are owned by the bootstrapper wallet.

**Comment by WangSecurity** [comment]
Adding to what the sponsor said, it's not a loss of funds or yield, it's just the team owning a part of the vault which is normal.

And afaik decisions from other contests don't really affect the judging/escalation decision, therefore, I don't think it's a valid argument (this sentence is solely about mentioning other contests results).

**Comment by MD-YashShah1923** [comment]
- But these shares cannot be claimed as they are bootstrapped to prevent inflation attack and the protocol team would not claim these bootstrapped shares leading to the problem as stated above by me.
- My main concern is that yield generated from big bootstrapped amount will lead to loss of yield funds for users as this yield is stolen from the actual suppliers as they cannot claim these yield.
- The yield generated from bootstrapped amount will keep on increasing as the share price increases creating a loss for actual users who can;t claim these yield.

**Comment by MD-YashShah1923** [comment]
> Adding to what the sponsor said, it's not a loss of funds or yield, it's just the team owning a part of the vault which is normal.
> 
> And afaik decisions from other contests don't really affect the judging/escalation decision, therefore, I don't think it's a valid argument (this sentence is solely about mentioning other contests results).

- It would be a loss for actual user's because yield generated from bootstrapped  would not be claimable by them.
- And bootstrapped amount being a big number Bootstrapped shares will have a bigger claim on the total asset percentage.

And i only mentioned the above cantina report for a reference .

**Comment by blablalf** [comment]
> > Adding to what the sponsor said, it's not a loss of funds or yield, it's just the team owning a part of the vault which is normal.
> > And afaik decisions from other contests don't really affect the judging/escalation decision, therefore, I don't think it's a valid argument (this sentence is solely about mentioning other contests results).
> 
> * It would be a loss for actual user's because yield generated from bootstrapped  would not be claimable by them.
> * And bootstrapped amount being a big number Bootstrapped shares will have a bigger claim on the total asset percentage.
> 
> And i only mentioned the above cantina report for a reference .

There would be no yield generated at bootstrap (the vault would be in open state, so our assets will just stay in the vault). The deposit is made by us, so the underlying is taken by us, the yield made on top of this underlying therefore doesn't belong to other users.

**Comment by MD-YashShah1923** [comment]
Yes i know the yield made on  bootstrapped tokens doesn't belong to other users. But this yield gets increased a lot when share price increases and this yield would stay up inside the contract only and this all things is happening because Bootstrapping amount is big and yield accrued would increase very much and will have bigger claim on the total asset percentage.

**Comment by blablalf** [comment]
> Yes i know the yield made on bootstrapped tokens doesn't belong to other users. But this yield gets increased a lot when share price increases and this yield would stay up inside the contract only and this all things is happening because Bootstrapping amount is big and yield accrued would increase very much and will have bigger claim on the total asset percentage.

Why would the yield increase?
There is no yield at all when we bootstrap. The assets are just waiting into the contract for the epoch to start.

**Comment by MD-YashShah1923** [comment]
> > Yes i know the yield made on bootstrapped tokens doesn't belong to other users. But this yield gets increased a lot when share price increases and this yield would stay up inside the contract only and this all things is happening because Bootstrapping amount is big and yield accrued would increase very much and will have bigger claim on the total asset percentage.
> 
> Why would the yield increase? There is no yield at all when we bootstrap. The assets are just waiting into the contract for the epoch to start.

- The yield won't increase at the bootstrap but it will increase gradually as the share price increases and this happens when other user deposits assets into vault and then vault generates yield , so as deposit or share price increases it would generate more yield.
- so the yield generated from bootstrapped amount would go in vain and always be in contract only .
- And as the bootstrapped amount is big it would have a bigger claim on the total withdraw asset percentage.

**Comment by blablalf** [comment]
> > > Yes i know the yield made on bootstrapped tokens doesn't belong to other users. But this yield gets increased a lot when share price increases and this yield would stay up inside the contract only and this all things is happening because Bootstrapping amount is big and yield accrued would increase very much and will have bigger claim on the total asset percentage.
> > 
> > 
> > Why would the yield increase? There is no yield at all when we bootstrap. The assets are just waiting into the contract for the epoch to start.
> 
> * The yield won't increase at the bootstrap but it will increase gradually as the share price increases and this happens when other user deposits assets into vault and then vault generates yield , so as deposit or share price increases it would generate more yield.
> * so the yield generated from bootstrapped amount would go in vain and always be in contract only .
> * And as the bootstrapped amount is big it would have a bigger claim on the total withdraw asset percentage.

> this happens when other user deposits assets into vault 
No it does not.

> and then vault generates yield
The vault will generate yield when it will be closed and settled/opened again, it will then generate yield for everyone according to the size of the deposit. The bootstrap is participating to the yield fabrication since the bootstrap liquidity (underlying) is at risk (working) into the strategy.

> so as deposit or share price increases
The deposits (amount and size) and the share price increase are not the same thing and are not linked.

> it would generate more yield
It would generate more yield for the vault, for the users, it will be the same proportion of yield according to what they deposited into it (the same proportion with or without bootstrap).

> so the yield generated from bootstrapped amount would go in vain and always be in contract only .
Actually we will own the bootsrapped shares/LP of the vault associated to the initial deposit since our underlying will also work into the strat. So if the strat generates yield our shares will gain value (in the same proportions of other users deposits).
I don't see why you speak about shares always in the contract.

> And as the bootstrapped amount is big it would have a bigger claim on the total withdraw asset percentage.
I don't see the problem with that, and we are speaking about dozens of millions of dollars into each vault, so for me 1k$ of bootstrap doesn't seem to be an enormous amount.

**Comment by blablalf** [comment]
> > > Yes i know the yield made on bootstrapped tokens doesn't belong to other users. But this yield gets increased a lot when share price increases and this yield would stay up inside the contract only and this all things is happening because Bootstrapping amount is big and yield accrued would increase very much and will have bigger claim on the total asset percentage.
> > 
> > 
> > Why would the yield increase? There is no yield at all when we bootstrap. The assets are just waiting into the contract for the epoch to start.
> 
> * The yield won't increase at the bootstrap but it will increase gradually as the share price increases and this happens when other user deposits assets into vault and then vault generates yield , so as deposit or share price increases it would generate more yield.
> * so the yield generated from bootstrapped amount would go in vain and always be in contract only .
> * And as the bootstrapped amount is big it would have a bigger claim on the total withdraw asset percentage.

> this happens when other user deposits assets into vault 

No it does not.

> and then vault generates yield

The vault will generate yield when it will be closed and settled/opened again, it will then generate yield for everyone according to the size of the deposit. The bootstrap is participating to the yield fabrication since the bootstrap liquidity (underlying) is at risk (working) into the strategy.

> so as deposit or share price increases

The deposits (amount and size) and the share price increase are not the same thing and are not linked.

> it would generate more yield

It would generate more yield for the vault, for the users, it will be the same proportion of yield according to what they deposited into it (the same proportion with or without bootstrap).

> so the yield generated from bootstrapped amount would go in vain and always be in contract only .

Actually we will own the bootsrapped shares/LP of the vault associated to the initial deposit since our underlying will also work into the strat. So if the strat generates yield our shares will gain value (in the same proportions of other users deposits).
I don't see why you speak about shares always in the contract.

> And as the bootstrapped amount is big it would have a bigger claim on the total withdraw asset percentage.

I don't see the problem with that, and we are speaking about dozens of millions of dollars into each vault, so for me 1k$ of bootstrap doesn't seem to be an enormous amount.

**Comment by MD-YashShah1923** [comment]
> > > > Yes i know the yield made on bootstrapped tokens doesn't belong to other users. But this yield gets increased a lot when share price increases and this yield would stay up inside the contract only and this all things is happening because Bootstrapping amount is big and yield accrued would increase very much and will have bigger claim on the total asset percentage.
> > > 
> > > 
> > > Why would the yield increase? There is no yield at all when we bootstrap. The assets are just waiting into the contract for the epoch to start.
> > 
> > 
> > 
> > * The yield won't increase at the bootstrap but it will increase gradually as the share price increases and this happens when other user deposits assets into vault and then vault generates yield , so as deposit or share price increases it would generate more yield.
> > * so the yield generated from bootstrapped amount would go in vain and always be in contract only .
> > * And as the bootstrapped amount is big it would have a bigger claim on the total withdraw asset percentage.
> 
> > this happens when other user deposits assets into vault
> 
> No it does not.
> 
> > and then vault generates yield
> 
> The vault will generate yield when it will be closed and settled/opened again, it will then generate yield for everyone according to the size of the deposit. The bootstrap is participating to the yield fabrication since the bootstrap liquidity (underlying) is at risk (working) into the strategy.
> 
> > so as deposit or share price increases
> 
> The deposits (amount and size) and the share price increase are not the same thing and are not linked.
> 
> > it would generate more yield
> 
> It would generate more yield for the vault, for the users, it will be the same proportion of yield according to what they deposited into it (the same proportion with or without bootstrap).
> 
> > so the yield generated from bootstrapped amount would go in vain and always be in contract only .
> 
> Actually we will own the bootsrapped shares/LP of the vault associated to the initial deposit since our underlying will also work into the strat. So if the strat generates yield our shares will gain value (in the same proportions of other users deposits). I don't see why you speak about shares always in the contract.
> 
> > And as the bootstrapped amount is big it would have a bigger claim on the total withdraw asset percentage.
> 
> I don't see the problem with that, and we are speaking about dozens of millions of dollars into each vault, so for me 1k$ of bootstrap doesn't seem to be an enormous amount.

Why you want to waste 1k$ if whole situation can be controlled by just bootstrapping 1000 wei of assets.
This big amount i guess would create problem in future.

**Comment by blablalf** [comment]
> > > > > Yes i know the yield made on bootstrapped tokens doesn't belong to other users. But this yield gets increased a lot when share price increases and this yield would stay up inside the contract only and this all things is happening because Bootstrapping amount is big and yield accrued would increase very much and will have bigger claim on the total asset percentage.
> > > > 
> > > > 
> > > > Why would the yield increase? There is no yield at all when we bootstrap. The assets are just waiting into the contract for the epoch to start.
> > > 
> > > 
> > > 
> > > * The yield won't increase at the bootstrap but it will increase gradually as the share price increases and this happens when other user deposits assets into vault and then vault generates yield , so as deposit or share price increases it would generate more yield.
> > > * so the yield generated from bootstrapped amount would go in vain and always be in contract only .
> > > * And as the bootstrapped amount is big it would have a bigger claim on the total withdraw asset percentage.
> > 
> > 
> > > this happens when other user deposits assets into vault
> > 
> > 
> > No it does not.
> > > and then vault generates yield
> > 
> > 
> > The vault will generate yield when it will be closed and settled/opened again, it will then generate yield for everyone according to the size of the deposit. The bootstrap is participating to the yield fabrication since the bootstrap liquidity (underlying) is at risk (working) into the strategy.
> > > so as deposit or share price increases
> > 
> > 
> > The deposits (amount and size) and the share price increase are not the same thing and are not linked.
> > > it would generate more yield
> > 
> > 
> > It would generate more yield for the vault, for the users, it will be the same proportion of yield according to what they deposited into it (the same proportion with or without bootstrap).
> > > so the yield generated from bootstrapped amount would go in vain and always be in contract only .
> > 
> > 
> > Actually we will own the bootsrapped shares/LP of the vault associated to the initial deposit since our underlying will also work into the strat. So if the strat generates yield our shares will gain value (in the same proportions of other users deposits). I don't see why you speak about shares always in the contract.
> > > And as the bootstrapped amount is big it would have a bigger claim on the total withdraw asset percentage.
> > 
> > 
> > I don't see the problem with that, and we are speaking about dozens of millions of dollars into each vault, so for me 1k$ of bootstrap doesn't seem to be an enormous amount.
> 
> Why you want to waste 1k$ if whole situation can be controlled by just bootstrapping 1000 wei of assets. This big amount i guess would create problem in future.

"Why you want to waste 1k$"
We don't waste it since these assets will work into the strategy. And if the vault end one day, we will be able to take these back. Again we are speaking about dozen of millions $ that will be deposited into the vaults so I don't think 1k$ is a big financial cost for Amphor Labs. I remind you that this audit is costing more than 20k$.

"This big amount i guess would create problem in future"
I cannot understand how and I would be grateful to you if you provide an explanation about this.
