### ISSUE TITLE
Myrault - Imperfect defense mechanism against inflation attack

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-amphor-judging#144]
Myrault

high

# Imperfect defense mechanism against inflation attack

## Summary
Imperfect defense mechanism against inflation attack

## Vulnerability Detail
The documentation mentions:

"We will boostrap the vault to avoid inflation attack so please take this into consideration."
For weth vault it would be 1 weth.
For usdc vault it would be 1000 usdc.

This still cannot reasonably defend against inflation attacks.

1. The way the `SyncSynthVault::_convertToShares` function  calculates shares is:`assets.mulDiv(totalSupply() + 1, totalAssets() + 1, rounding);` https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L568-L585 
```solidity
    /**
     * @dev Internal conversion function (from assets to shares) with support
     * for rounding direction.
     * @param assets Theunderlying assets amount to be converted into shares.
     * @param rounding The rounding direction.
     * @return Amount of shares received in exchange of the specified underlying
     * assets amount.
     */
    function _convertToShares(
        uint256 assets,
        Math.Rounding rounding
    )
        internal
        view
        returns (uint256)
    {
        return assets.mulDiv(totalSupply() + 1, totalAssets() + 1, rounding);
    }
```

**Virtual shares are not introduced here to increase the attacker’s attack costs.**

2. In the `SyncSynthVault::deposit` function, https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L291-L317

```solidity
    /**
     * @dev See {IERC4626-deposit}
     * @notice The `deposit` function is used to deposit underlying assets into
     * the vault.
     * @param assets The underlying assets amount to be converted into shares.
     * @param receiver The address of the shares receiver.
     * @return Amount of shares received in exchange of the
     * specified underlying assets amount.
     */
    function deposit(
        uint256 assets,
        address receiver
    )
        public
        whenNotPaused
        returns (uint256)
    {
        uint256 maxAssets = maxDeposit(receiver);
        if (assets > maxAssets) {
            revert ERC4626ExceededMaxDeposit(receiver, assets, maxAssets);
        }

        uint256 sharesAmount = previewDeposit(assets);
        _deposit(_msgSender(), receiver, assets, sharesAmount);

        return sharesAmount;
    }
```

**If the calculated sharesAmount is 0, there is no revert**

Although both weth vault and usdc vault will be boostrapped, the initialized amount is not enough to defend against inflation attack.

## Impact
inflation attack

## Code Snippet
1. **Virtual shares are not introduced here to increase the attacker’s attack costs.**
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L568-L585
2. **If the calculated sharesAmount is 0, there is no revert**
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L291-L317

## Tool used

Manual Review

## Recommendation
On this basis, two new checks should be added:

1. If the user deposits, share calculation returns zero, then revert directly
5. Add a virtual shares mechanism to increase the attacker's cost, so that the numerator in the share calculation formula `assets * totalSupply +1eVirtualOffset / totalAssets +1` will be raised by us. If the attacker wants to raise the denominator of totalAssets through malicious donations , then he will pay a greater cost

**Comment by Myrault9** [comment]
Escalate

I think it is possible for the attacker to recover the cost. In other words, the cost of the attack is not necessarily higher than imagined, because the donated assets can be partially recovered through redeem. Let me briefly describe the process, and please let me know if I'm wrong:

The project party said that the contract will be bootstrapped. Let’s take 1000 USDC as an example. At this time, totalAssets is 1000 USDC and totalSupply is 1000 shares.
The attacker also deposits approximately the same amount of assets, such as depositing 1000 USDC, and obtains 1000 shares. At this time, totalAssets is 2000 USDC, and totalSupply is 2000 shares.
The attacker donates a large amount of assets, such as 1_000_000_000 USDC (the purpose here is to donate assets exceeding the amount deposited by most normal users), then totalAssets is 1_000_002_000 and totalSupply is 2000 shares (of which the attacker holds 1000 shares) , and subsequent calls to the redeem function can recover the assets cost corresponding to these 1000 shares)
There is a very critical step here. In this process, there may be other people who want to deposit, but the number is not large. For example, a normal user Alice wants to depost 1000 USDC, and she expects to get 1000 shares. . However, due to assets.mulDiv(totalSupply() + 1, totalAssets() + 1, rounding); in the _convertToShares function, the calculation is 1000*(2000+1)/(1_000_002_000+1), and 0 shares are obtained. This is why I always emphasize that if the calculated shares are 0, it should be revert. This is an important step in the attack process. In this case, the victim is not actually the contract project party, but other people involved in the deposit. In most cases, these people involved in the deposit will not deposit a particularly large amount, so in this case, they always will get 0 share.

Moreover, in this process, Alice's deposit of 1000 USDC will also help the attacker to continuously increase the price of shares, because Alice's deposit of 1000 USDC results in totalAssets += 1000 and totalSupply += 0. Because the _convertToAssets function is as follows shares.mulDiv(totalAssets() + 1, totalSupply() + 1, rounding);, as long as the number of molecules (totalAssets) continues to increase, the price of share will continue to increase. If there are enough victims like Alice, then the attacker may be able to recoup the cost of the initial donation. This is a mathematical problem. I will not calculate here how many victims are required to deposit and how many times for the attacker to hold. Shares are enough to recover the cost. I only express the possibility of this matter.

Therefore, I sincerely suggest that it is reasonable to reconsider this report, because during the entire attack process, the 1000 USDC of the project boostrap was not actually the main attack target. The core attack target of the attacker was other depositors, that is, Saying that this will lead to a denial of service to a certain extent (if we consider it from the perspective of a DOS attack, as a competitor, if I want to destroy the deposit function of the entire contract, can I do it regardless of the cost?), the people who deposit this part will always Obtaining 0 shares, this is a critical part of the vulnerability. And considering the attack process I mentioned above, the attacker has the possibility of recovering the cost (or the cost of the attack is not high)

Based on the above points, I think this is a valid bug report, at least dup of issues129:
https://github.com/sherlock-audit/2024-03-amphor-judging/issues/129

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think it is possible for the attacker to recover the cost. In other words, the cost of the attack is not necessarily higher than imagined, because the donated assets can be partially recovered through redeem. Let me briefly describe the process, and please let me know if I'm wrong:
> 
> The project party said that the contract will be bootstrapped. Let’s take 1000 USDC as an example. At this time, totalAssets is 1000 USDC and totalSupply is 1000 shares.
> The attacker also deposits approximately the same amount of assets, such as depositing 1000 USDC, and obtains 1000 shares. At this time, totalAssets is 2000 USDC, and totalSupply is 2000 shares.
> The attacker donates a large amount of assets, such as 1_000_000_000 USDC (the purpose here is to donate assets exceeding the amount deposited by most normal users), then totalAssets is 1_000_002_000 and totalSupply is 2000 shares (of which the attacker holds 1000 shares) , and subsequent calls to the redeem function can recover the assets cost corresponding to these 1000 shares)
> There is a very critical step here. In this process, there may be other people who want to deposit, but the number is not large. For example, a normal user Alice wants to depost 1000 USDC, and she expects to get 1000 shares. . However, due to assets.mulDiv(totalSupply() + 1, totalAssets() + 1, rounding); in the _convertToShares function, the calculation is 1000*(2000+1)/(1_000_002_000+1), and 0 shares are obtained. This is why I always emphasize that if the calculated shares are 0, it should be revert. This is an important step in the attack process. In this case, the victim is not actually the contract project party, but other people involved in the deposit. In most cases, these people involved in the deposit will not deposit a particularly large amount, so in this case, they always will get 0 share.
> [18:21]
> Moreover, in this process, Alice's deposit of 1000 USDC will also help the attacker to continuously increase the price of shares, because Alice's deposit of 1000 USDC results in totalAssets += 1000 and totalSupply += 0. Because the _convertToAssets function is as follows shares.mulDiv(totalAssets() + 1, totalSupply() + 1, rounding);, as long as the number of molecules (totalAssets) continues to increase, the price of share will continue to increase. If there are enough victims like Alice, then the attacker may be able to recoup the cost of the initial donation. This is a mathematical problem. I will not calculate here how many victims are required to deposit and how many times for the attacker to hold. Shares are enough to recover the cost. I only express the possibility of this matter.
> 
> Therefore, I sincerely suggest that it is reasonable to reconsider this report, because during the entire attack process, the 1000 USDC of the project boostrap was not actually the main attack target. The core attack target of the attacker was other depositors, that is, Saying that this will lead to a denial of service to a certain extent (if we consider it from the perspective of a DOS attack, as a competitor, if I want to destroy the deposit function of the entire contract, can I do it regardless of the cost?), the people who deposit this part will always Obtaining 0 shares, this is a critical part of the vulnerability. And considering the attack process I mentioned above, the attacker has the possibility of recovering the cost (or the cost of the attack is not high)
> 
> If you think there is any part of my understanding that is wrong, feel free to let me know, thank you very much

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by WangSecurity** [comment]
I believe that issue should remain low. Yes, I see and understand the point above. If the user donates 1bn of USDC, other users won't receive any funds, but In that exact scenario, users total assets amount in the contract has to be 2bn of USDC so the attacker will only breakeven (cause half of the shares are controlled by the bootstrapper). Therefore, I believe it should remain low, cause attacker has to donate ENORMOUS amount of assets to the contract for this to happen. Moreover, there's a functionality to withdraw the funds from the protocol by the owner. Thus, I believe the team would notice, withdraw all the funds, send back to the users manually and reset the vault.

Therefore, I see that it is mathematically possible based on the calculation, but realistically it's infeasible to pull off such attack. Hence, low/info.
