### ISSUE TITLE
buggsy - DepositPermit functions can lead to loss of user funds

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-amphor-judging#17]
buggsy

high

# DepositPermit functions can lead to loss of user funds

## Summary
The vault implements Depositwithpermit functions  however, the vault’s underlying asset is intended to be Weth , usdc and u expect to interact with the following assets - weth, usdc, usdt, wbtc .
in the case of  WETH does not. Surprisingly, when permit is called on WETH, the function call will execute without any errors.

This is because the fallback inside WETH is execute when permit is called.
 
## Vulnerability Detail - 
Alice gives infinite approval  to spend WETH
Alice calls depositwithPermit and etc , deposits 1 WETH into the Vault
Attacker calls depositWithPermit, passes an empty signature and transfers all tokens from Alice into the vault , crediting the attacker for the deposit.
Attacker withdraws all tokens credited to him.

## Impact 
For reference on this issue - 
https://solidity-by-example.org/hacks/weth-permit/ 

## Code Snippet -https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L327-L338 , 
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L532-L546 ,
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L277-L290

## Tool used - 

Manual Review

## Recommendation -  Instead Use '' Permit2''  they have dealt with this issue .

Duplicate of #19

**Comment by DanielNedelchev** [comment]
yes the way the report is made is a mistake of mine saw the contest in the last hours of it  , i thought the resource provided is self evident for the impact . A malicious user crediting an honest's user deposit to himself and withdrawing it , is " opportunity lost" ? So because users can interact with the protocol via non permit functions automatically invalided the potential loss of funds to user that GIVE Aprovals to Amphor to spend their WETH and Everyday Users give infinite approvals to protocols they deem trustible because its more gas efficient and less tedious .
