### ISSUE TITLE
Dudex_2004 - The `depositWithPermit` function is allowed to be called by the permit creator only

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#23]
Dudex_2004

medium

# The `depositWithPermit` function is allowed to be called by the permit creator only

Dudex_2004

medium

## Summary
Function `depositWithPermit` is allowed to be called by the permit creator only. Not any other contracts will be able to execute these function on behalf of signer.

## Vulnerability Detail
The `depositWithPermit` function is allowed to provide a signed permit in order to receive, approve and deposit funds into the vault.

```javascript
function depositWithPermit(
        uint256 assets,
        address receiver,
        PermitParams calldata permitParams
    )
        external
        returns (uint256)
    {
        if (_asset.allowance(msg.sender, address(this)) < assets) {
            execPermit(_msgSender(), address(this), permitParams);
        }
        return deposit(assets, receiver);
    }
```
This function calls `exePermit` and pass `msg.sender` as `_owner` to that function.

```javascript
function execPermit(
        address owner,
        address spender,
        PermitParams calldata permitParams
    )
        internal
    {
        ERC20Permit(address(_asset)).permit(
            owner,
            spender,
            permitParams.value,
            permitParams.deadline,
            permitParams.v,
            permitParams.r,
            permitParams.s
        );
    }
```

This means, that the signer can be only the same person that called `depositWithPermit` function.

However, the purpose of the permit is to allow someone to sign the approve signature, so that this signature can be used by another contract to call some function on behalf of signer.

In this case, anyone should be able to sign permit for the vault, and vault should check that `receiver` is same who signed permit.

## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L277C5-L289C6
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L550C5-L566C6

## Tool used

Manual Review

## Recommendation
Use `receiver` instead of `msg.sender`.

```javascript
function depositWithPermit(
        uint256 assets,
        address receiver,
        PermitParams calldata permitParams
    )
        external
        returns (uint256)
    {
        if (_asset.allowance(receiver, address(this)) < assets) {
            execPermit(receiver, address(this), permitParams);
        }
        return deposit(assets, receiver);
    }
```

**Comment by DuDeXsUraj** [comment]
why this issue did not get any reward?

**Comment by DuDeXsUraj** [comment]
Escalate

I'm escalating this issue on behalf of @0xShax2nk.in for the following reasons he provided:

The issue falls under medium severity indeed, as the current implementation restricts the use of the permit to the signer only, defeating the purpose of the permit system which is meant to delegate the ability to perform actions on the signer's behalf.

There is an inconsistency in the use of permits with the depositWithPermit function:

The execPermit function is called with _msgSender() as the owner, implying that the caller of depositWithPermit must be the permit signer.
The intended use of permits is to allow a third party to execute actions with the signer's approval without requiring the signer to be the caller.
I see the comment left during judging,

another goal of permit is to create off-chain approvals; plus I don't see it breaking core functionality of the contract; yeah it would be more convenient; but it's a design advice -> info/low

I disagree with the comment, even if another goal of permit is to create off-chain approvals, the full potential of this feature includes not just creating off-chain approvals but also enabling third parties to use these approvals on-chain on behalf of the signer. off-chain approvals are a goal, they should not compromise the intended security model of the permit system, which includes delegating the execution of approved actions.

Also I don't consider it as design advice, rather the logic(code) should be corrected in order to keep consistency with the ERC20 permit standard. Deviating from the standard's typical implementation could lead to compatibility issues with wallets and other smart contracts that expect the standard behavior and this implies the one of the core feature of contract is restricted.

The solution is simple is to Modify the depositWithPermit function to accept the permit signer's address as an argument and use it in the execPermit call instead of _msgSender(), as recommended in mitigation of the original report.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I'm escalating this issue on behalf of @0xShax2nk.in for the following reasons he provided:
> 
> The issue falls under medium severity indeed, as the current implementation restricts the use of the permit to the signer only, defeating the purpose of the permit system which is meant to delegate the ability to perform actions on the signer's behalf.
> 
> There is an inconsistency in the use of permits with the depositWithPermit function:
> 
> The execPermit function is called with _msgSender() as the owner, implying that the caller of depositWithPermit must be the permit signer.
> The intended use of permits is to allow a third party to execute actions with the signer's approval without requiring the signer to be the caller.
> I see the comment left during judging,
> 
> another goal of permit is to create off-chain approvals; plus I don't see it breaking core functionality of the contract; yeah it would be more convenient; but it's a design advice -> info/low
> 
> I disagree with the comment, even if another goal of permit is to create off-chain approvals, the full potential of this feature includes not just creating off-chain approvals but also enabling third parties to use these approvals on-chain on behalf of the signer. off-chain approvals are a goal, they should not compromise the intended security model of the permit system, which includes delegating the execution of approved actions.
> 
> Also I don't consider it as design advice, rather the logic(code) should be corrected in order to keep consistency with the ERC20 permit standard. Deviating from the standard's typical implementation could lead to compatibility issues with wallets and other smart contracts that expect the standard behavior and this implies the one of the core feature of contract is restricted.
> 
> The solution is simple is to Modify the depositWithPermit function to accept the permit signer's address as an argument and use it in the execPermit call instead of _msgSender(), as recommended in mitigation of the original report.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by DuDeXsUraj** [comment]
Escalate

I'm escalating this issue on behalf of @0xShax2nk.in for the following reasons he provided:

The issue falls under medium severity indeed, as the current implementation restricts the use of the permit to the signer only, defeating the purpose of the permit system which is meant to delegate the ability to perform actions on the signer's behalf.

There is an inconsistency in the use of permits with the depositWithPermit function:

The execPermit function is called with _msgSender() as the owner, implying that the caller of depositWithPermit must be the permit signer.
The intended use of permits is to allow a third party to execute actions with the signer's approval without requiring the signer to be the caller.
I see the comment left during judging,

another goal of permit is to create off-chain approvals; plus I don't see it breaking core functionality of the contract; yeah it would be more convenient; but it's a design advice -> info/low

I disagree with the comment, even if another goal of permit is to create off-chain approvals, the full potential of this feature includes not just creating off-chain approvals but also enabling third parties to use these approvals on-chain on behalf of the signer. off-chain approvals are a goal, they should not compromise the intended security model of the permit system, which includes delegating the execution of approved actions.

Also I don't consider it as design advice, rather the logic(code) should be corrected in order to keep consistency with the ERC20 permit standard. Deviating from the standard's typical implementation could lead to compatibility issues with wallets and other smart contracts that expect the standard behavior and this implies the one of the core feature of contract is restricted.

The solution is simple is to Modify the depositWithPermit function to accept the permit signer's address as an argument and use it in the execPermit call instead of _msgSender(), as recommended in mitigation of the original report.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I'm escalating this issue on behalf of @0xShax2nk.in for the following reasons he provided:
> 
> The issue falls under medium severity indeed, as the current implementation restricts the use of the permit to the signer only, defeating the purpose of the permit system which is meant to delegate the ability to perform actions on the signer's behalf.
> 
> There is an inconsistency in the use of permits with the depositWithPermit function:
> 
> The execPermit function is called with _msgSender() as the owner, implying that the caller of depositWithPermit must be the permit signer.
> The intended use of permits is to allow a third party to execute actions with the signer's approval without requiring the signer to be the caller.
> I see the comment left during judging,
> 
> another goal of permit is to create off-chain approvals; plus I don't see it breaking core functionality of the contract; yeah it would be more convenient; but it's a design advice -> info/low
> 
> I disagree with the comment, even if another goal of permit is to create off-chain approvals, the full potential of this feature includes not just creating off-chain approvals but also enabling third parties to use these approvals on-chain on behalf of the signer. off-chain approvals are a goal, they should not compromise the intended security model of the permit system, which includes delegating the execution of approved actions.
> 
> Also I don't consider it as design advice, rather the logic(code) should be corrected in order to keep consistency with the ERC20 permit standard. Deviating from the standard's typical implementation could lead to compatibility issues with wallets and other smart contracts that expect the standard behavior and this implies the one of the core feature of contract is restricted.
> 
> The solution is simple is to Modify the depositWithPermit function to accept the permit signer's address as an argument and use it in the execPermit call instead of _msgSender(), as recommended in mitigation of the original report.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by 0xHacker2684** [comment]
Escalate

I'm escalating this issue on behalf of @Dudex_2004 .in for the following reasons he provided:

The issue falls under medium severity indeed, as the current implementation restricts the use of the permit to the signer only, defeating the purpose of the permit system which is meant to delegate the ability to perform actions on the signer's behalf.

There is an inconsistency in the use of permits with the depositWithPermit function:

The execPermit function is called with _msgSender() as the owner, implying that the caller of depositWithPermit must be the permit signer.
The intended use of permits is to allow a third party to execute actions with the signer's approval without requiring the signer to be the caller.
I see the comment left during judging,

another goal of permit is to create off-chain approvals; plus I don't see it breaking core functionality of the contract; yeah it would be more convenient; but it's a design advice -> info/low

I disagree with the comment, even if another goal of permit is to create off-chain approvals, the full potential of this feature includes not just creating off-chain approvals but also enabling third parties to use these approvals on-chain on behalf of the signer. off-chain approvals are a goal, they should not compromise the intended security model of the permit system, which includes delegating the execution of approved actions.

Also I don't consider it as design advice, rather the logic(code) should be corrected in order to keep consistency with the ERC20 permit standard. Deviating from the standard's typical implementation could lead to compatibility issues with wallets and other smart contracts that expect the standard behavior and this implies the one of the core feature of contract is restricted.

The solution is simple is to Modify the depositWithPermit function to accept the permit signer's address as an argument and use it in the execPermit call instead of _msgSender(), as recommended in mitigation of the original report.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I'm escalating this issue on behalf of @Dudex_2004 .in for the following reasons he provided:
> 
> The issue falls under medium severity indeed, as the current implementation restricts the use of the permit to the signer only, defeating the purpose of the permit system which is meant to delegate the ability to perform actions on the signer's behalf.
> 
> There is an inconsistency in the use of permits with the depositWithPermit function:
> 
> The execPermit function is called with _msgSender() as the owner, implying that the caller of depositWithPermit must be the permit signer.
> The intended use of permits is to allow a third party to execute actions with the signer's approval without requiring the signer to be the caller.
> I see the comment left during judging,
> 
> another goal of permit is to create off-chain approvals; plus I don't see it breaking core functionality of the contract; yeah it would be more convenient; but it's a design advice -> info/low
> 
> I disagree with the comment, even if another goal of permit is to create off-chain approvals, the full potential of this feature includes not just creating off-chain approvals but also enabling third parties to use these approvals on-chain on behalf of the signer. off-chain approvals are a goal, they should not compromise the intended security model of the permit system, which includes delegating the execution of approved actions.
> 
> Also I don't consider it as design advice, rather the logic(code) should be corrected in order to keep consistency with the ERC20 permit standard. Deviating from the standard's typical implementation could lead to compatibility issues with wallets and other smart contracts that expect the standard behavior and this implies the one of the core feature of contract is restricted.
> 
> The solution is simple is to Modify the depositWithPermit function to accept the permit signer's address as an argument and use it in the execPermit call instead of _msgSender(), as recommended in mitigation of the original report.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
