### ISSUE TITLE
sammy - Claiming a deposit in the same Epoch in which the deposit was requested will lead to loss of funds

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-amphor-judging#70]
sammy

high

# Claiming a deposit in the same Epoch in which the deposit was requested will lead to loss of funds

## Summary
A user who has made a deposit request using the [`requestDeposit`](https://github.com/AmphorProtocol/asynchronous-vault/blob/c4f7a9b8f3d3d9aba0e43eaae38ef9b556023b0e/src/AsyncSynthVault.sol#L439) function will forfeit their entire balance if they attempt to claim the deposit using the [`claimDeposit`](https://github.com/AmphorProtocol/asynchronous-vault/blob/c4f7a9b8f3d3d9aba0e43eaae38ef9b556023b0e/src/AsyncSynthVault.sol#L508) function within the same Epoch.

## Vulnerability Detail
Within the `AsyncSynthVault` in its closed state, users can initiate a deposit through the [`requestDeposit`](https://github.com/AmphorProtocol/asynchronous-vault/blob/c4f7a9b8f3d3d9aba0e43eaae38ef9b556023b0e/src/AsyncSynthVault.sol#L439) function. Subsequently, they would use the [`claimDeposit`](https://github.com/AmphorProtocol/asynchronous-vault/blob/c4f7a9b8f3d3d9aba0e43eaae38ef9b556023b0e/src/AsyncSynthVault.sol#L508) function to claim vault shares. However, executing this claim within the same Epoch as the deposit request results in the total loss of the user's balance.

The issue unfolds as follows:
1. The user invokes the [`requestDeposit`](https://github.com/AmphorProtocol/asynchronous-vault/blob/c4f7a9b8f3d3d9aba0e43eaae38ef9b556023b0e/src/AsyncSynthVault.sol#L439) function, transferring a specified amount of tokens (`assets`) to the vault. This triggers the [`_createDepositRequest`](https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L698) function, which increases `epochs[epochId].depositRequestBalance[receiver]` by the `assets` amount.
2. Subsequently, the user calls the [`claimDeposit`](https://github.com/AmphorProtocol/asynchronous-vault/blob/c4f7a9b8f3d3d9aba0e43eaae38ef9b556023b0e/src/AsyncSynthVault.sol#L508) function. This action invokes the [`_claimDeposit`](https://github.com/AmphorProtocol/asynchronous-vault/blob/c4f7a9b8f3d3d9aba0e43eaae38ef9b556023b0e/src/AsyncSynthVault.sol#L742) internal function, setting `epochs[lastRequestId].depositRequestBalance[receiver]` to 0, where `lastRequestId` is equal to `epochId`. However, the user is not credited with any shares, as `previewClaimDeposit` yields 0.

Proof of Code :

The following test demonstrates the claim made above : 
```solidity
function test_poc() external {
        
        // set token balances
        deal(vaultTested.asset(), user1.addr, 20);
        deal(vaultTested.asset(), user2.addr, type(uint256).max); 
        
        // initial deposit when vault is open
        vm.startPrank(user2.addr);
        IERC20Metadata(vaultTested.asset()).approve(address(vaultTested), 10);
        vaultTested.deposit(10, user2.addr);
        vm.stopPrank();
        
        // owner closes the vault 
        vm.prank(vaultTested.owner());
        vaultTested.close();

        vm.startPrank(user1.addr);
        IERC20Metadata(vaultTested.asset()).approve(address(vaultTested), 20);
        // user1 requests a deposit
        vaultTested.requestDeposit(20, user1.addr, user1.addr,  "");
        assertEq(vaultTested.pendingDepositRequest(user1.addr),20); // check pending deposit
        // user1 claims the deposit
        vaultTested.claimDeposit(user1.addr);
        // user1 checks the pending deposit request amount
        assertEq(vaultTested.pendingDepositRequest(user1.addr),0);
        // user1 checks shares balance
        assertEq(vaultTested.balanceOf(user1.addr), 0);
       // user1 checks tokens balance
        assertEq(IERC20Metadata(vaultTested.asset()).balanceOf(user1.addr), 0); 

        vm.stopPrank();

        // all three are zero, indicating loss of funds

    }
```
To run the test : 
1. Copy the above code and paste it into `TestClaimDeposit.t.sol`
2. Run `forge test --match-test test_poc --ffi`

## Impact
The user loses both their initial deposit of tokens and the vault shares that they were entitled to receive.

## Tool used
Manual Review
Foundry

## Recommendation
Revert [`claimDeposit`](https://github.com/AmphorProtocol/asynchronous-vault/blob/c4f7a9b8f3d3d9aba0e43eaae38ef9b556023b0e/src/AsyncSynthVault.sol#L508) if `lastRequestId == epochId`

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/103

**Comment by realfugazzi** [comment]
@WangSecurity this should be a duplicate of https://github.com/sherlock-audit/2024-03-amphor-judging/issues/72

**Comment by 0xLogos** [comment]
Escalate

Agree with comment above

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Agree with comment above

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by sammy-tm** [comment]
From what I can see in issue #72, both the issues with `claimAndRequestDeposit` and the claim functions have been highlighted in one issue; however, the root cause of these issues is different, and most Watsons have reported the vulnerabilities in `claimAndRequestDeposit` and the claim functions separately. Therefore, they should be treated as separate issues.

**Comment by realfugazzi** [comment]
> From what I can see in issue #72, both the issues with `claimAndRequestDeposit` and the claim functions have been highlighted in one issue; however, the root cause of these issues is different, and most Watsons have reported the vulnerabilities in `claimAndRequestDeposit` and the claim functions separately. Therefore, they should be treated as separate issues.

In that case, to be fair, watsons that reported both issues in one report should have duplicate participation in both issues (70 and 72).

**Comment by WangSecurity** [comment]
What sammy said above was actually the reason, why I mead them separate, but I totally agree with the comment from fugazzi above. But I still believe they should be separate issues.

The reason is that I believe there is flaw in `claimAndRequestDeposit` as well, therefore, this one and #72 should be 2 different issues.

**Comment by sammy-tm** [comment]
I agree with @realfugazzi that his report should be included in both separate issues and rewarded for the same.

**Comment by realfugazzi** [comment]
> What sammy said above was actually the reason, why I mead them separate, but I totally agree with the comment from fugazzi above. But I still believe they should be separate issues.
> 
> The reason is that I believe there is flaw in `claimAndRequestDeposit` as well, therefore, this one and #72 should be 2 different issues.

Could you mark #72 also as a valid duplicate of this one (#70)? How can this be corrected? Thanks

**Comment by WangSecurity** [comment]
I think the only way they can by connected is accepting escalations, but as I said above, I'm still of the opinion that these two remain separated.

**Comment by KedziaPawel** [comment]
they are not duplicates, they have a different root cause

**Comment by Evert0x** [comment]
It's not possible to reward a single report for two issues, will revisit this situation later.

**Comment by zzykxx** [comment]
I agree with the escalation, #70 and #72 should be grouped together. The root cause in both instances is that claiming deposits on the same epoch they have been requested on leads to loss of funds.

@WangSecurity what is the flaw in `claimAndRequestDeposit` that makes you believe this should be separated?

**Comment by sammy-tm** [comment]
@zzykxx , The reason both of these are separate issues is as follows : 

Issue 1 : Vulnerability in the claim functions, wherein these lack a check allowing users to claim deposits/redeems in the same epoch and inadvertently lose their balance.
Issue 2 : Vulnerability in the `claimAndRequestDeposit`, which allows an unauthorized user to call the `claimDeposit` function on behalf of another person. This issue _can_ also leverage Issue 1 to grief a user, as described in #72; however, this issue exists as a separate entity.

There is a mismatch between Watsons who have found issues 1 and 2. Most Watsons have reported these separately, and those who have identified issue 1, haven't necessarily identified issue 2. This would make it unfair to mark these issues as dupes, as in my unbiased opinion, issue 1 was much easier to find than issue 2. Issue 2 involves a more complex attack path and not everyone that found issue 1, was necessarily able to identify issue 2 and come up with said attack path.

**Comment by zzykxx** [comment]
> @zzykxx , The reason both of these are separate issues is as follows :
> Issue 2 : Vulnerability in the `claimAndRequestDeposit`, which allows an unauthorized user to call the `claimDeposit` function on behalf of another person. This issue _can_ also leverage Issue 1 to grief a user, as described in #72; however, this issue exists as a separate entity.

What is the loss of funds that happens if "an unauthorized user calls the `claimDeposit` function on behalf of another person" when  the "claiming deposits on the same epoch issue" is fixed?

**Comment by sammy-tm** [comment]
@zzykxx 
I think if the "claiming deposits in the same epoch" issue is fixed, the severity of the `claimAndRequestDeposit` issue would definitely decrease. However, this would still be a matter of concern as an attacker still has control over _when_ a user chooses to claim their deposits. A user may refrain from claiming deposits in certain epochs due to various reasons, including their **(investment strategies?)**. Therefore, letting this bug hang around could cause issues and losses for specific use cases, or in cases where for example, claiming in a certain epoch gives the attacker an advantage and causes severe losses for the party involved. However, I will leave this argument about 'the severity in case the former issue is fixed' open for now.

>Issue 1 : Vulnerability in the claim functions, wherein these lack a check allowing users to claim deposits/redeems in the same epoch and inadvertently lose their balance.
>Issue 2 : Vulnerability in the claimAndRequestDeposit, which allows an unauthorized user to call the claimDeposit function on behalf of another person. This issue can also leverage Issue 1 to grief a user, as described in https://github.com/sherlock-audit/2024-03-amphor-judging/issues/72; however, this issue exists as a separate entity.

Additionally, I would like to point out that, marking both these issues as dupes would mean that Watsons who identified issue 1 also found the vulnerability in the `claimAndRequestDeposit` and the ability to leverage issue 1 to cause severe loss of funds for the user. The latter involves a more complex attack path and not everyone that found issue 1 was able to identify issue 2. In my opinion, issue 1 was much easier to identify for the majority. Duping both of these would be blatantly unfair to Watsons who dove deeper into the code, found issue 2, and engineered a complex attack path leveraging issue 1.

**Comment by Evert0x** [comment]
I think there are two separate issues
1) Same epoch claim deposit issue
2) Incorrect `claimAndRequestDeposit()` behavior, seems like #65 is a good report that isolates that issue.

I believe 1) should be High severity and 2) Medium severity.

**Comment by zzykxx** [comment]
I still don't understand the implications of claiming on behalf of another user besides doing him a favor. Anyway, all reports that mention both issues should have duplicate participation. This includes mine #13.

**Comment by Evert0x** [comment]
> I still don't understand the implications of claiming on behalf of another user besides doing him a favor. 

@WangSecurity do you have a better understanding of the implications?

**Comment by WangSecurity** [comment]
I understand that if we didn't have the problem with losing funds if claim/redeem in the same epoch, then the issue of claiming deposits on behalf of other users is at max low/info. But I still don't think these two (70 and 72) should be grouped up as duplicates, because the issue with stealing the funds involves an additional knob (claiming on behalf of other users).

I can see the point that they have the same fix techincally, and under rules they should be duplicates, but on the other hand, we can invalidate issue 70 and its dups due to user mistake (they shouldn't try to claim in the same epoch). Obviously, I don't actaully mean to invalidate 70, but if we decide to duplicate them due to the same fix, then 70 can be invalidated under rules as well and issue 72 should remain valid.

And I think the decision suggested from @Evert0x above is the best here. But if we decide to duplicate them due to the same fix, then I'll accept.

And adding on implications, yes the losers don't lose funds, but I feel like it can be viewed as a core functionality break, cause the attacker can claim on their behalf when they shouldn't. No one loses, no one profits, but it may be a core functionality break (I'm unsure and just raising another point).

**Comment by sammy-tm** [comment]
>Issue 1 : Vulnerability in the claim functions, wherein these lack a check allowing users to claim deposits/redeems in the same epoch and inadvertently lose their balance.
Issue 2 : Vulnerability in the claimAndRequestDeposit, which allows an unauthorized user to call the claimDeposit function on behalf of another person. This issue can also leverage Issue 1 to grief a user, as described in https://github.com/sherlock-audit/2024-03-amphor-judging/issues/72; however, this issue exists as a separate entity.

Let's assume that Issue 1 has been fixed and let's isolate the implications of issue 2 : 

NOT all users may choose to claim their deposits instantly. Moreover, whenever a user claims their deposits, they are subject to the exchange rate calculated at the end of the last epoch. Thus, how many shares a user receives is dependent on THAT exchange rate. So the amount of shares received by the user is variable, depending on the epoch in which they claim their deposits. 
Now this can easily be controlled by a malicious user as there is no access modifier for `_claimDeposit` in `claimAndRequestDeposit` and they could claim shares on behalf of other users on a large scale without any cost (only gas fee). 

This is just an example of an attack from the top of my head, but I could probably think and write a detailed attack path for this if needed.

Not only does this break the core functionality of the protocol, but it also risks user funds. This issue should be tagged as at least a 'medium' if not 'high'

**Comment by Evert0x** [comment]
Planning to reject escalation and sort into the following two families

High severity
```
70 (report)
5
13
31
44
66
75
98
99
134
22
16
72
115
```

Medium Severity
```
65 (report)
33
43
69
76
132
```

**Comment by WangSecurity** [comment]
@Evert0x will I get a penalty for this escalation? Essentially, it's rejected, but the severity of one of the families is changed from what I've initially decided.

**Comment by zzykxx** [comment]
@Evert0x what about people that reported both issues in one report?

Edit: #65 states "If the receiver address has an open position, he will be liquidated." What is the reasoning behind categorizing it in the medium severity group and marking it as the best report?

Edit2: #43, #69, #76, #132 all mention an attacker can force users to lose their deposit. Why is this classified as medium severity? The only report in the current "Medium severity" category that doesn't mention this is #33, will this report earn x10 the others because the submitter was not able to identify the highest possible impact?

**Comment by sammy-tm** [comment]
I personally feel that reports that identified the complex attack path leveraging both issues deserve more credit than being clubbed with reports that don't.

**Comment by zzykxx** [comment]
> I personally feel that reports that identified the complex attack path leveraging both issues deserve more credit than being clubbed with reports that don't.

By Sherlock rules the reports that:
- identified claiming on the same epoch leads to loss of funds
- identified an attacker can force an user to lose funds by claiming on his behalf on the same epoch

Should be grouped because the root cause is the same. 

This leaves out the reports that identified the possibility of claiming on behalf of another user but doesn't state anything about an attacker forcing them to lose funds by claiming on the same epoch (ex. #33).

**Comment by Evert0x** [comment]
@zzykxx Issue 65 isolates the issue, while other reports don't. So it would be the clearest issue for the report.

All the others mention both issues, I proposed them to organize like this so this doesn't happen.

> will this report earn x10 the others because the submitter was not able to identify the highest possible impact?

**Comment by zzykxx** [comment]
I still think these should be grouped together but because the judges both seem aligned on them being separate (and judges have the final say) I'd like make sure they are at least separated correctly.

As far as I understand the judges proposal is to separate the issues this way:
1. Issues that regard users themselves claiming on the same epoch and losing funds.
2. Issues that regard an attacker enforcing the bug described in `1` by calling `claimAndRequestDeposit()`.
3. Issues that regard an attacker claiming on behalf of another user by calling `claimAndRequestDeposit()` but without enforcing the bug described in `1`.

There are 3 categories because [#33](https://github.com/sherlock-audit/2024-03-amphor-judging/issues/33) doesn't explicitly state that an attacker can enforce a loss so it's not correct to classify this with `2`.

This is my opinion on severities:
- Issues `1` are high severity, it can't be considered a user mistake because we can't expect users to know that they will lose funds when they call a function named `claimDeposit()` at the wrong time.
- Issues `2` are high severity, an attacker can enforce a loss on users.
- Issues `3` are medium severity, an attacker can claim on behalf of another user at a time that is not convenient for the user.

This is why I think it's hard to categorize everything correctly:
- People that submitted issue `1` are not aware of either `2` or `3`.
- People that submitted issue `2`, are aware of both `1` and `3`. They are aware of `1` because they abuse the same bug and they are aware of `3` because they abuse the possibility of claiming on behalf of somebody else.
- People that submitted issue `3` are not aware of either `1` or `2`.


In my opinion people that submitted issue `2` should have duplicate participation in both `1` and `3`.

**Comment by Evert0x** [comment]
After a discussion and acquiring full context on this specific part of the code and the reports. I believe the right choice is to group all the issues together that describe the "same epoch" issue as a High severity family.

My previous comment stated that 65 isolated the other issue (Incorrect `claimAndRequestDeposit()` behavior) well. However, I believe that the report fails to describe an issue that would hit the criteria for Medium or High severity. It might not even be an issue, just a design choice. 

Planning to accept escalation and create the following family (all issues together except 65)

72 -- best, since it even has POCs for both scenarios, and duplicates are , 5, 13, 16, 22, 31, 33, 43, 44, 66, 69, 70, 75, 76, 98, 99, 115, 132, 134. High severity

**Comment by Evert0x** [comment]
Result:
High 
Duplicate of #72

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xLogos](https://github.com/sherlock-audit/2024-03-amphor-judging/issues/70/#issuecomment-2025430462): accepted

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
