### ISSUE TITLE
14si2o_Flint - maxDeposit is in breach of EIP4626 Standard and invalidate check in deposit function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-amphor-judging#91]
14si2o_Flint

medium

# maxDeposit is in breach of EIP4626 Standard and invalidate check in deposit function

## Summary

In the `SyncSynthVault` contract, the `maxDeposit` function returns `type(uint256).max`, which is a clear-cut breach of the EIP4626 Standard since this is vastly higher than the actual maximum that would be accepted and will cause a revert.  

This also partially invalidates the `maxDeposit` check in the `deposit` function. 

## Vulnerability Detail

From the [EIP4626](https://eips.ethereum.org/EIPS/eip-4626#methods) Standard: 

```solidity
For maxDeposit:
MUST return the maximum amount of assets deposit would allow to be deposited for receiver and not cause a revert, 
which MUST NOT be higher than the actual maximum that would be accepted (it should underestimate if necessary).   
This assumes that the user has infinite assets, i.e. MUST NOT rely on balanceOf of asset.

```
Given that a user has infinite assets, the functions should return a value that MUST be accepted. Yet, we can see from the function code below, it returns `type(uint256).max`, a value which can easily exceed the theoretical total supply of the planned vaults by a factor of magnitude.

For example, the protocol plans to deploy a vault with [wBTC](https://www.coingecko.com/en/coins/wrapped-bitcoin). Since the maximum theoretical supply of wrapped BTC cannot be higher then the supply of [BTC](https://www.coingecko.com/en/coins/bitcoin), the absolute limit, even with infinite assets, is **21,000,000**.   

As such, the value returned will always cause a revert, which is a clear violation of the EIP4626 Standard. 

```solidity
    function maxDeposit(address) public view returns (uint256) {
        return vaultIsOpen && !paused() ? type(uint256).max : 0;
    }

    function deposit(
        uint256 assets,
        address receiver
    )
        public
        whenNotPaused
        returns (uint256)
    {
        uint256 maxAssets = maxDeposit(receiver);
        if (assets > maxAssets) {
            revert ERC4626ExceededMaxDeposit(receiver, assets, maxAssets);
        }

        uint256 sharesAmount = previewDeposit(assets);
        _deposit(_msgSender(), receiver, assets, sharesAmount);

        return sharesAmount;
    }
```
## Impact

1. Breach of EIP4626 Standard
2. The `maxDeposit` in the `deposit` function is ineffective since it will allow values that are impossible. In it's current state it only checks against deposits while the protocol is paused or the vault is closed.

## Code Snippet

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L402-L411

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L419-L421

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L300-L317

## Tool used

Manual Review

## Recommendation

Change the function so that it will return the max supply the vault asset.

**Comment by Arabadzhiew** [comment]
Escalate

In the comments of [this](https://github.com/sherlock-audit/2024-01-napier-judging/issues/96) issue from the Napier contest, it was stated by the Head of Judging that issues about mentioned EIPs are valid, and that the appropriate changes will be made to the rules in the future in order to reflect that.

Combining this with the fact that in the README of this contest it is clearly stated that the protocol is intended to comply with EIP4626 leads me to believe that this issue is a valid medium severity one.

**Comment by WangSecurity** [comment]
Sorry, haven't seen that situation in the Napier contest and the changes haven't been made to the docs yet, but I still think this one should remain invalid (low severity), cause it doesn't break any functionality or loss of funds. Also the rule in sherlock's docs that if there are no external integrations, then non-compliance is informational. And here I don't see any external integration.

**Comment by 14si2o** [comment]
I'd like to add a few points. 

This is clearly a valid medium since the protocol EXPLICITLY stated that it must be compliant with EIP4626. Previous cases such as the Napier which @Arabadzhiew mentioned and [Tokemak](https://solodit.xyz/issues/m-6-previewredeem-and-redeem-functions-deviate-from-the-erc4626-specification-sherlock-tokemak-git) fully support this position. 

The Sherlock rules (which are outdated per Head of Judging) mention external integrations **and** the absence of adverse effect. 

Amphor is an automated yield aggregator using ERC4626 Vaults. If successful, it will be used by numerous parties (users/bot/protocols) who fully rely on the correct implementation of EIP4626. It is the most fundamental security guarantee an erc4626 protocol must give. Incorrect implementation of this leads to failings checks and reverting deposits, thereby directly damaging the trust in the protocol and it's chances of success. How on earth is that not an adverse effect?   

Honestly, this shouldn't even be a discussion. When an ERC4626 protocol, which EXPLICITLY states it must implement EIP4626, is found in breach of EIP4626, then YES it is a valid medium. Aside from the adverse effects mentioned, the mere reputation damage that this would cause for the protocol, would cripple any changes for success.

**Comment by WangSecurity** [comment]
@14si2o I want to ask several questions so I can better understand it, it seems that there's something that I'm missing.

But as I mentioned EIP4626 standard says "For maxDeposit:
MUST return the maximum amount of assets deposit would allow to be deposited for receiver and not cause a revert,"

In our case, maxDeposit returns `type(uint256).max`, how it will cause a revert? Can users deposit more than `type(uint256).max`?

Taking the example with WBTC, it has a cap of 21,000,000 tokens and 6 decimals, but it's lower than `type(uint256).max`, so, won't cause any revert, therefore looks alright to me.

Or this means that `maxDeposit` should be set at the exact amount of tokens that can be created? But, ETH, USDC and USDT don't have maxSupply (checked on Coingecko).

What I'm trying to say here is that to me it looks fine (maybe I'm wrong) because it actually returns the amount of assets deposit would allow to be deposited for receiver and not cause a revert. To cause a revert users have to deposit more than `type(uint256).max`, and to me it looks unfeasible.

Please correct if I'm wrong, but I actually don't see where's the violation of EIP 4626 standard.

**Comment by 14si2o** [comment]
The violation of EIP4626 is clear if you include the second line of the standard you quoted: 

"MUST return the maximum amount of assets deposit would allow to be deposited for receiver and not cause a revert, 
which MUST NOT be higher than the actual maximum that would be accepted (it should underestimate if necessary)."

Must not be higher than the actual maximum!

So for WBTC, the theoretical maximum deposit given infinite money should be  21_000_000*1e6.
However, they return type(uint256).max, which roughly is 1_157_920 * e72.

It should be clear that returning a value that is several magnitudes greater than the actual maximum, is a clear-cut violation of the EIP4626 Standard.

**Comment by WangSecurity** [comment]
Yeah, it answers my question, thank you very much. Then another question here, what this incompliance leads to, like what would happen?

The `maxDepoit` is `type(uint256).max` which is higher than it should be according to EIP4626. But, how it would harm anyone? Yeah, I see in your previous comment you say "it will be used by numerous parties (users/bot/protocols) who fully rely on the correct implementation of EIP4626". But how it would harm those users exactly?

Can you give example (if several than even better) of how it harms other? Maybe they will get unexpected reverts? 

I ask those questions cause I don't really understand how it harms anyone that `maxDeposit == type(uint256).max` and not the exact total supply of the token. 

Again thank you for the comments, looking forward to your answers!

**Comment by 14si2o** [comment]
I have explained in detail, in the finding and in the comments, how the EIP4626 standard is violated, why such a violation should be considered a valid medium finding for protocols that explicitly state that they should be compliant with EIP4626 and the previous cases which fully support this position. 

I do not believe there is anything left to add or to explain. I will await the evaluation of the Head of Judging.

**Comment by WangSecurity** [comment]
14si2o I don't say you're completely wrong and I see where the compliance with EIP4626 is not perfect, but, unfortunately, I don't see it as medium, but I really try to get it. Therefore, I'm asking for help from you to make me also understand it in the most clear way. Also, if you help me and I agree with you, then there's a higher chance of escalation being accepter!

Thus, I want to again ask how this incompliancy harms those users/protocol exactly?

Can you give example (if several than even better) of how it harms other? Maybe they will get unexpected reverts?

Again, I don't say you're completely wrong, I'm just trying to completely understand your point. Hope you'll see what I mean here and we'll be able to succefully resolve this situation.

**Comment by Evert0x** [comment]
> which MUST NOT be higher than the actual maximum that would be accepted

The contract is able to accept more than 21 million bitcoin, right? I don't see this a clear violation of this sentence in the 4626 standard.

Planning to reject escalation and keep issue state as is @14si2o

**Comment by Evert0x** [comment]
Result:
Unique
Invalid

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Arabadzhiew](https://github.com/sherlock-audit/2024-03-amphor-judging/issues/91/#issuecomment-2025026961): rejected
