### ISSUE TITLE
0xKartikgiri00 - Slippage controls for `SyncSynthVault::Mint()` and `SyncSynthVault::deposit()` functions are missing.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#92]
0xKartikgiri00

medium

# Slippage controls for `SyncSynthVault::Mint()` and `SyncSynthVault::deposit()` functions are missing.

## Summary
Missing of slippage control in `SyncSynthVault::Mint()` and `SyncSynthVault::deposit()` functions can cause griefing attack to user.

## Vulnerability Detail
As per EIP4626 states "If implementors intend to support EOA account access directly, they should consider adding an additional function call for deposit/mint/withdraw/redeem with the means to accommodate slippage loss or unexpected deposit/withdrawal limits, since they have no other means to revert the transaction if the exact output amount is not achieved."

As the slippage is not defined will cost the the user to spent much more asset amount than expected if calls `mint` functions or will get much lesser asset amount than expected if calls the `deposit` function.

## Impact
The impact on user is that it will cost the user to spent much more asset amount or will get the much lesser asset amount than expected.

## Proof Of Concept
The concept and case for `SyncSynthVault::deposit()` functions is similar to this.

BOB wants to mint 1e18 shares tokens in exchange for sending  1e18 asset tokens.
Yet, such `SyncSynthVault::mint` function call causes 1.2e18 assets tokens to be transferred from BOB.
BOB unexpectedly sends 0.2e18 more asset tokens than expected for minting 1e18 shares tokens.

## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L300

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L329

## Tool used
Manual Review

## Recommendation
The recommendation is to include a mechanism in deposit function that allows msg.sender to specify the minimum shares to be minted for calling the corresponding `SyncSynthVault:_deposit` function; calling such `deposit` function should revert if the corresponding `SyncSynthVault:_deposit` function's shares output is less than the specified minimum shares to be minted. Similarly, a mechanism should be include in `SyncSynthVault::mint` function that allows msg.sender to specify the maximum asset tokens to be sent for calling the corresponding  `SyncSynthVault:_deposit` function; calling such `SyncSynthVault::mint` function should revert if the function's assets output is more than the specified maximum asset tokens to be sent.

**Comment by kartik-giri** [comment]
> assets tokens to be trans

I have just given an example.

**Comment by kartik-giri** [comment]
## Proof Of Concept

1. In `mint` function the user expecting the asset amount which will be transfer from user in exchange of share tokens by calling `previewMint` by passing shares amount whihc user wants to mint.
```javascript
  uint256 assetsAmount = previewMint(shares);
```

2. The user can end up giving much asset amount than expected by `previewMint` function. How let's see.

3. Let's say when the user was planning to mint the shares token the ratio of shares and asset token were 1:1.
```javascript
   function previewMint(uint256 shares) public view returns (uint256) {
        return _convertToAssets(shares, Math.Rounding.Ceil); //convert shares in to asssets
    }
```

4. The user expecting 100 shares tokens in transfer of 100 amount token.

5. But cause the `previewMint` function calculating the asset amount using `_convertToAssets` function which is also using  `balanceof` function to get asset token balance of this contract.

`_convertToAssets` function.
```javascript
 function _convertToAssets(
        uint256 shares,
        Math.Rounding rounding
    )
        internal
        view
        returns (uint256)
    {   
        //totalAssets()+1 => This function returns the total amount of underlying assets held by the vault.
        //totalSupply()+1 => The total share tokens in the supply.+ 1
        return shares.mulDiv(totalAssets() + 1, totalSupply() + 1, rounding);
    }
```
`totalAssets` function:
```javascript
 function totalAssets() public view returns (uint256) {
        //@Question well vaultIsOpen would be always true cause we do not have setter function for it yet!
        if (vaultIsOpen) return _asset.balanceOf(address(this)); ///return underlying token balance of this contract
        else return _asset.balanceOf(address(this)) + lastSavedBalance; //@Question but where we are setting lastSavedBalance cause if we not it is 0.
    }
```


6. Any malicious attacker can frontrun the user and send the amount of asset token directly to this contract and fluctuate the price to grief the genuine user.

7. After front running lets say the ratio of asset and shares tokens is now 1.2 : 1

8. So when the user tx will be execute the `mint` function will run `previewMint` again and return the 120 asset token in return of 100 shares token. which was 1:1 before the attack.

8. So that's how the user will end up transferring 20 more asset tokens more return of 100 shares token.

9. And that's why we need the slippage control in our all functions  deposit/mint/withdraw/redeem.

The same concept valid for mint, withdraw and redeem function.

**Comment by kartik-giri** [comment]
And it is valid according to sherlock rules:-
"Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high"

**Comment by WangSecurity** [comment]
@kartik-giri PoC is good and it shows how the user can lose funds (and it is what I would like to see initially when you submit issues, cause when you say "unexpectedly sends more" doesn't really show anything).

And you can ask someone to escalate, but I still believe it's a low, cause it's a grief attack, I don't see how an attacker can profit from this attack. Also when the vault becomes bigger and has more funds, the cost will become exponentially higher and I don't see any incentives for this to occur. But again, I agree that it can happen, tho think it should remain low.

**Comment by kartik-giri** [comment]
@WangSecurity You said it should remain low. But according to sherlock rules it should be valid "Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high".

And you are admitting "user can lose funds".

**Comment by kartik-giri** [comment]
escalate

**Comment by sherlock-admin2** [comment]
>  escalate

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by kartik-giri** [comment]
![Screenshot (156)](https://github.com/sherlock-audit/2024-03-amphor-judging/assets/109913085/d7d1d6c5-5114-4462-a2c6-7fe5160b735d)

I have nothing to say now.
escalate

**Comment by sherlock-admin2** [comment]
> ![Screenshot (156)](https://github.com/sherlock-audit/2024-03-amphor-judging/assets/109913085/d7d1d6c5-5114-4462-a2c6-7fe5160b735d)
> 
> I have nothing to say now.
> escalate

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by WangSecurity** [comment]
I will again say why I think this issue should remain invalid.

To pull of such attack the attacker has to provide 10x more value and lose it all. For example, if user deposits 100 usdc, the attacker has to transfer 500 usdc for the user to lose 50 dollars.

The problem is that the attacker won't be able to retrieve those funds, therefore, they just lose. Imagine how much it would take if the user deposits WETH. Therefore, I believe this issue should remain low (I want to highlight, I don't say it's completely wrong, but I don't think it's enough for M/H).

**Comment by kartik-giri** [comment]
@WangSecurity The question is will user lose it's funds, If this attack happens? Yes I am pretty sure it will.

And that's why it is valid and totally according to sherlock rules. 

Your whole argument is attacker would not get any benefit from this attack and attacker would never do this. But the whole point of greifing attack is to greif the user. So I think this attack scenerio is also valid cause there is no protection in code to save the user from this kind of slippage attack.

And I don't know as "judge" why you are not considering the sherlock rules where it is clearly written.
![Screenshot (156)](https://github.com/sherlock-audit/2024-03-amphor-judging/assets/109913085/bcc53c1c-78f1-44be-9a41-14411b8346ad)

**Comment by WangSecurity** [comment]
@kartik-giri after an additional discussion with the sponsor we saw that the user can withdraw all the funds they've initially deposited. For example, if they wanted to deposit 100 USDC for 100 shares, and ended up 150 USDC for 100 shares, they can withdraw all those 150 USDC, or in the worst case it'll be 149 USDC due to `+1` in calculations. Therefore, it's invalid cause there'e no loss as well.

In you need, I can send the withdraw calculations or you can make them yourself.

**Comment by kartik-giri** [comment]
> @kartik-giri after an additional discussion with the sponsor we saw that the user can withdraw all the funds they've initially deposited. For example, if they wanted to deposit 100 USDC for 100 shares, and ended up 150 USDC for 100 shares, they can withdraw all those 150 USDC, or in the worst case it'll be 149 USDC due to `+1` in calculations. Therefore, it's invalid cause there'e no loss as well.
> 
> In you need, I can send the withdraw calculations or you can make them yourself.

thanks
